### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by okj203** [moodln/new_wave#5]
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contain wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + ex. Probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by okj203** [comment]
- [ ] `GET /api/users/artistsFollowing` doesn't need to be nested, instead, you can make the index method of your users controller return all the artists that the current user is following by writing as `GET /api/users` (unless you need the users' index method for something else)
- [ ] `GET /api/users/genresLiked` wouldn't be necessary in the backend, since `GET /api/users/:id` should return all the info of a specific user

**Comment by moodln** [comment]
I changed it so that `GET /api/users/:id` will return artistsFollowing and genresLiked for that particular user... I realized that it didn't actually make sense to have the `GET /api/users/artistsFollowing` because 'artistsFollowing' was attached to the entirety of 'users' instead of a specific user :')

**Comment by okj203** [comment]
- [ ] You also need some backend routes for your album entity, so that you can render all the songs that belong to a particular album. It says that your `GET /api/songs/albumId` "returns all songs for a particular album, used for artist show page and search index" but you can accomplish this through albums controller. Each album should have `.songs` association method which should return all the songs that belong to a particular album.

**Comment by moodln** [comment]
makes much more sense than what i had - thank you !!
